version: "2.2"

# Flink "Session Mode"  Deployment configuration


#volumes:
#  flink-vol:

services:
  jobmanager:
    image: flink:latest
    ports:
      - "8081:8081"
    command: jobmanager
    environment:
      - |
        FLINK_PROPERTIES=
        jobmanager.rpc.address: jobmanager        
    volumes:
      - ./flink-data:/opt/flink/flink-data


  taskmanager:
    image: flink:latest
    depends_on:
      - jobmanager
    command: taskmanager
    scale: 1
    environment:
      - |
        FLINK_PROPERTIES=
        jobmanager.rpc.address: jobmanager
        taskmanager.numberOfTaskSlots: 2
            volumes:
    volumes:
      - ./flink-data:/opt/flink/flink-data